# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site text constant (and localization settings)
title:
  ru: heX - добро пожаловать в блог программиста
  en: heX - welcome to the blog of the programmer

#description: # (in footer)
#  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
#  fr: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.

index: # main page
  ru: index.html
  en: index-en.html
feed: # RSS
  ru: /feed.xml
  en: /feed-en.xml

# https://jekyllrb.com/docs/collections
collections:
  pages:
    # permalink explain:
    #  ":collection"-> collection name (for example: "pages")
    #  ":path"-> path in collection exclude file name (for example: "programs")
    #  path to file "_pages/programs/myprogram.md", result: "./pages/programs/myprogram.html
    permalink: "/:collection/:path/"
    output: true

# default value for pages
#---
#layout: page
#---
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page


# Site system settings
baseurl: "" # - empty. the subpath of your site, e.g. /blog
timezone: Europe/Moscow
url: "http://hex.name" # the base hostname & protocol for your site

# account
# twitter_username: hex1625616
github_username: hex16
email: hex1625616@gmail.com

# Build settings
markdown: kramdown
